INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NM, PRODUCT_PRC) values (8878, 'Nike Shoe', 50.65);
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NM, PRODUCT_PRC) values (8879, 'Adidaas Shoe', 54.65);

INSERT INTO ORDER_ITEM(ORDER_ITEM_ID, ORDER_DT, PRODUCT_ID) values (1, SYSDATE, 8878);
INSERT INTO ORDER_ITEM(ORDER_ITEM_ID, ORDER_DT, PRODUCT_ID) values (2, SYSDATE, 8878);
INSERT INTO ORDER_ITEM(ORDER_ITEM_ID, ORDER_DT, PRODUCT_ID) values (3, SYSDATE, 8879);
INSERT INTO ORDER_ITEM(ORDER_ITEM_ID, ORDER_DT, PRODUCT_ID) values (4, SYSDATE, 8879);
