INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NM, PRODUCT_PRC) values (1, 'Nike Shoe', 20.42);
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NM, PRODUCT_PRC) values (2, 'Adidas Shoe', 60.50);

INSERT INTO ORDER_ITEM(ORDER_ITEM_ID, ORDER_DT, PRODUCT_ID) values (1, '2020-06-11', 1);
INSERT INTO ORDER_ITEM(ORDER_ITEM_ID, ORDER_DT, PRODUCT_ID) values (2, '2020-06-11', 1);
INSERT INTO ORDER_ITEM(ORDER_ITEM_ID, ORDER_DT, PRODUCT_ID) values (3, '2020-06-11', 2);
INSERT INTO ORDER_ITEM(ORDER_ITEM_ID, ORDER_DT, PRODUCT_ID) values (4, '2020-06-11', 2);
